// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateAccessRes interface {
	createAccessRes()
}

type CreateApprovalRes interface {
	createApprovalRes()
}

type CreateAuditRes interface {
	createAuditRes()
}

type CreateMissionRes interface {
	createMissionRes()
}

type CreateRequestRes interface {
	createRequestRes()
}

type CreateRocketRes interface {
	createRocketRes()
}

type DeleteAccessRes interface {
	deleteAccessRes()
}

type DeleteApprovalRes interface {
	deleteApprovalRes()
}

type DeleteAuditRes interface {
	deleteAuditRes()
}

type DeleteMissionRes interface {
	deleteMissionRes()
}

type DeleteRequestRes interface {
	deleteRequestRes()
}

type DeleteRocketRes interface {
	deleteRocketRes()
}

type ListAccessRes interface {
	listAccessRes()
}

type ListApprovalRes interface {
	listApprovalRes()
}

type ListAuditRes interface {
	listAuditRes()
}

type ListMissionRequestsRes interface {
	listMissionRequestsRes()
}

type ListMissionRes interface {
	listMissionRes()
}

type ListRequestRes interface {
	listRequestRes()
}

type ListRocketMissionsRes interface {
	listRocketMissionsRes()
}

type ListRocketRes interface {
	listRocketRes()
}

type ReadAccessApprovalsRes interface {
	readAccessApprovalsRes()
}

type ReadAccessRes interface {
	readAccessRes()
}

type ReadApprovalRequestsRes interface {
	readApprovalRequestsRes()
}

type ReadApprovalRes interface {
	readApprovalRes()
}

type ReadAuditRes interface {
	readAuditRes()
}

type ReadMissionRes interface {
	readMissionRes()
}

type ReadMissionRocketRes interface {
	readMissionRocketRes()
}

type ReadRequestMissionRes interface {
	readRequestMissionRes()
}

type ReadRequestRes interface {
	readRequestRes()
}

type ReadRocketRes interface {
	readRocketRes()
}

type UpdateAccessRes interface {
	updateAccessRes()
}

type UpdateApprovalRes interface {
	updateApprovalRes()
}

type UpdateAuditRes interface {
	updateAuditRes()
}

type UpdateMissionRes interface {
	updateMissionRes()
}

type UpdateRequestRes interface {
	updateRequestRes()
}

type UpdateRocketRes interface {
	updateRocketRes()
}
