// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"

	"github.com/go-faster/jx"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateAccess implements createAccess operation.
//
// Creates a new Access and persists it to storage.
//
// POST /accesses
func (UnimplementedHandler) CreateAccess(ctx context.Context, req *CreateAccessReq) (r CreateAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateApproval implements createApproval operation.
//
// Creates a new Approval and persists it to storage.
//
// POST /approvals
func (UnimplementedHandler) CreateApproval(ctx context.Context, req *CreateApprovalReq) (r CreateApprovalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAudit implements createAudit operation.
//
// Creates a new Audit and persists it to storage.
//
// POST /audits
func (UnimplementedHandler) CreateAudit(ctx context.Context, req *CreateAuditReq) (r CreateAuditRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMission implements createMission operation.
//
// Creates a new Mission and persists it to storage.
//
// POST /missions
func (UnimplementedHandler) CreateMission(ctx context.Context, req *CreateMissionReq) (r CreateMissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRequest implements createRequest operation.
//
// Creates a new Request and persists it to storage.
//
// POST /requests
func (UnimplementedHandler) CreateRequest(ctx context.Context, req *CreateRequestReq) (r CreateRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRocket implements createRocket operation.
//
// Creates a new Rocket and persists it to storage.
//
// POST /rockets
func (UnimplementedHandler) CreateRocket(ctx context.Context, req *CreateRocketReq) (r CreateRocketRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAccess implements deleteAccess operation.
//
// Deletes the Access with the requested ID.
//
// DELETE /accesses/{id}
func (UnimplementedHandler) DeleteAccess(ctx context.Context, params DeleteAccessParams) (r DeleteAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteApproval implements deleteApproval operation.
//
// Deletes the Approval with the requested ID.
//
// DELETE /approvals/{id}
func (UnimplementedHandler) DeleteApproval(ctx context.Context, params DeleteApprovalParams) (r DeleteApprovalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAudit implements deleteAudit operation.
//
// Deletes the Audit with the requested ID.
//
// DELETE /audits/{id}
func (UnimplementedHandler) DeleteAudit(ctx context.Context, params DeleteAuditParams) (r DeleteAuditRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMission implements deleteMission operation.
//
// Deletes the Mission with the requested ID.
//
// DELETE /missions/{id}
func (UnimplementedHandler) DeleteMission(ctx context.Context, params DeleteMissionParams) (r DeleteMissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRequest implements deleteRequest operation.
//
// Deletes the Request with the requested ID.
//
// DELETE /requests/{id}
func (UnimplementedHandler) DeleteRequest(ctx context.Context, params DeleteRequestParams) (r DeleteRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRocket implements deleteRocket operation.
//
// Deletes the Rocket with the requested ID.
//
// DELETE /rockets/{id}
func (UnimplementedHandler) DeleteRocket(ctx context.Context, params DeleteRocketParams) (r DeleteRocketRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAccess implements listAccess operation.
//
// List Accesses.
//
// GET /accesses
func (UnimplementedHandler) ListAccess(ctx context.Context, params ListAccessParams) (r ListAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListApproval implements listApproval operation.
//
// List Approvals.
//
// GET /approvals
func (UnimplementedHandler) ListApproval(ctx context.Context, params ListApprovalParams) (r ListApprovalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAudit implements listAudit operation.
//
// List Audits.
//
// GET /audits
func (UnimplementedHandler) ListAudit(ctx context.Context, params ListAuditParams) (r ListAuditRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMission implements listMission operation.
//
// List Missions.
//
// GET /missions
func (UnimplementedHandler) ListMission(ctx context.Context, params ListMissionParams) (r ListMissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMissionRequests implements listMissionRequests operation.
//
// List attached Requests.
//
// GET /missions/{id}/requests
func (UnimplementedHandler) ListMissionRequests(ctx context.Context, params ListMissionRequestsParams) (r ListMissionRequestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRequest implements listRequest operation.
//
// List Requests.
//
// GET /requests
func (UnimplementedHandler) ListRequest(ctx context.Context, params ListRequestParams) (r ListRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRocket implements listRocket operation.
//
// List Rockets.
//
// GET /rockets
func (UnimplementedHandler) ListRocket(ctx context.Context, params ListRocketParams) (r ListRocketRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRocketMissions implements listRocketMissions operation.
//
// List attached Missions.
//
// GET /rockets/{id}/missions
func (UnimplementedHandler) ListRocketMissions(ctx context.Context, params ListRocketMissionsParams) (r ListRocketMissionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadAccess implements readAccess operation.
//
// Finds the Access with the requested ID and returns it.
//
// GET /accesses/{id}
func (UnimplementedHandler) ReadAccess(ctx context.Context, params ReadAccessParams) (r ReadAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadAccessApprovals implements readAccessApprovals operation.
//
// Find the attached Access of the Access with the given ID.
//
// GET /accesses/{id}/approvals
func (UnimplementedHandler) ReadAccessApprovals(ctx context.Context, params ReadAccessApprovalsParams) (r ReadAccessApprovalsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadApproval implements readApproval operation.
//
// Finds the Approval with the requested ID and returns it.
//
// GET /approvals/{id}
func (UnimplementedHandler) ReadApproval(ctx context.Context, params ReadApprovalParams) (r ReadApprovalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadApprovalRequests implements readApprovalRequests operation.
//
// Find the attached Request of the Approval with the given ID.
//
// GET /approvals/{id}/requests
func (UnimplementedHandler) ReadApprovalRequests(ctx context.Context, params ReadApprovalRequestsParams) (r ReadApprovalRequestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadAudit implements readAudit operation.
//
// Finds the Audit with the requested ID and returns it.
//
// GET /audits/{id}
func (UnimplementedHandler) ReadAudit(ctx context.Context, params ReadAuditParams) (r ReadAuditRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadMission implements readMission operation.
//
// Finds the Mission with the requested ID and returns it.
//
// GET /missions/{id}
func (UnimplementedHandler) ReadMission(ctx context.Context, params ReadMissionParams) (r ReadMissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadMissionRocket implements readMissionRocket operation.
//
// Find the attached Rocket of the Mission with the given ID.
//
// GET /missions/{id}/rocket
func (UnimplementedHandler) ReadMissionRocket(ctx context.Context, params ReadMissionRocketParams) (r ReadMissionRocketRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadRequest implements readRequest operation.
//
// Finds the Request with the requested ID and returns it.
//
// GET /requests/{id}
func (UnimplementedHandler) ReadRequest(ctx context.Context, params ReadRequestParams) (r ReadRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadRequestMission implements readRequestMission operation.
//
// Find the attached Mission of the Request with the given ID.
//
// GET /requests/{id}/mission
func (UnimplementedHandler) ReadRequestMission(ctx context.Context, params ReadRequestMissionParams) (r ReadRequestMissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadRocket implements readRocket operation.
//
// Finds the Rocket with the requested ID and returns it.
//
// GET /rockets/{id}
func (UnimplementedHandler) ReadRocket(ctx context.Context, params ReadRocketParams) (r ReadRocketRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAccess implements updateAccess operation.
//
// Updates a Access and persists changes to storage.
//
// PATCH /accesses/{id}
func (UnimplementedHandler) UpdateAccess(ctx context.Context, req *UpdateAccessReq, params UpdateAccessParams) (r UpdateAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateApproval implements updateApproval operation.
//
// Updates a Approval and persists changes to storage.
//
// PATCH /approvals/{id}
func (UnimplementedHandler) UpdateApproval(ctx context.Context, req *UpdateApprovalReq, params UpdateApprovalParams) (r UpdateApprovalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAudit implements updateAudit operation.
//
// Updates a Audit and persists changes to storage.
//
// PATCH /audits/{id}
func (UnimplementedHandler) UpdateAudit(ctx context.Context, req jx.Raw, params UpdateAuditParams) (r UpdateAuditRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMission implements updateMission operation.
//
// Updates a Mission and persists changes to storage.
//
// PATCH /missions/{id}
func (UnimplementedHandler) UpdateMission(ctx context.Context, req *UpdateMissionReq, params UpdateMissionParams) (r UpdateMissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRequest implements updateRequest operation.
//
// Updates a Request and persists changes to storage.
//
// PATCH /requests/{id}
func (UnimplementedHandler) UpdateRequest(ctx context.Context, req *UpdateRequestReq, params UpdateRequestParams) (r UpdateRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRocket implements updateRocket operation.
//
// Updates a Rocket and persists changes to storage.
//
// PATCH /rockets/{id}
func (UnimplementedHandler) UpdateRocket(ctx context.Context, req *UpdateRocketReq, params UpdateRocketParams) (r UpdateRocketRes, _ error) {
	return r, ht.ErrNotImplemented
}
