// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/orbit-ops/mission-control/ent/access"
	"github.com/orbit-ops/mission-control/ent/approval"
	"github.com/orbit-ops/mission-control/ent/audit"
	"github.com/orbit-ops/mission-control/ent/request"
	"github.com/orbit-ops/mission-control/ent/rocket"
	"github.com/orbit-ops/mission-control/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accessFields := schema.Access{}.Fields()
	_ = accessFields
	// accessDescRolledBack is the schema descriptor for rolled_back field.
	accessDescRolledBack := accessFields[3].Descriptor()
	// access.DefaultRolledBack holds the default value on creation for the rolled_back field.
	access.DefaultRolledBack = accessDescRolledBack.Default.(bool)
	// accessDescID is the schema descriptor for id field.
	accessDescID := accessFields[0].Descriptor()
	// access.DefaultID holds the default value on creation for the id field.
	access.DefaultID = accessDescID.Default.(func() uuid.UUID)
	approvalFields := schema.Approval{}.Fields()
	_ = approvalFields
	// approvalDescRevoked is the schema descriptor for revoked field.
	approvalDescRevoked := approvalFields[4].Descriptor()
	// approval.DefaultRevoked holds the default value on creation for the revoked field.
	approval.DefaultRevoked = approvalDescRevoked.Default.(bool)
	// approvalDescID is the schema descriptor for id field.
	approvalDescID := approvalFields[0].Descriptor()
	// approval.DefaultID holds the default value on creation for the id field.
	approval.DefaultID = approvalDescID.Default.(func() uuid.UUID)
	auditFields := schema.Audit{}.Fields()
	_ = auditFields
	// auditDescAction is the schema descriptor for action field.
	auditDescAction := auditFields[1].Descriptor()
	// audit.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	audit.ActionValidator = auditDescAction.Validators[0].(func(string) error)
	// auditDescAuthor is the schema descriptor for author field.
	auditDescAuthor := auditFields[2].Descriptor()
	// audit.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	audit.AuthorValidator = auditDescAuthor.Validators[0].(func(string) error)
	// auditDescID is the schema descriptor for id field.
	auditDescID := auditFields[0].Descriptor()
	// audit.DefaultID holds the default value on creation for the id field.
	audit.DefaultID = auditDescID.Default.(func() string)
	requestFields := schema.Request{}.Fields()
	_ = requestFields
	// requestDescID is the schema descriptor for id field.
	requestDescID := requestFields[0].Descriptor()
	// request.DefaultID holds the default value on creation for the id field.
	request.DefaultID = requestDescID.Default.(func() uuid.UUID)
	rocketFields := schema.Rocket{}.Fields()
	_ = rocketFields
	// rocketDescImage is the schema descriptor for image field.
	rocketDescImage := rocketFields[2].Descriptor()
	// rocket.ImageValidator is a validator for the "image" field. It is called by the builders before save.
	rocket.ImageValidator = rocketDescImage.Validators[0].(func(string) error)
}
