// Code generated by ent, DO NOT EDIT.

package request

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/orbit-ops/mission-control/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldID, id))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldReason, v))
}

// Requester applies equality check predicate on the "requester" field. It's identical to RequesterEQ.
func Requester(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldRequester, v))
}

// MissionID applies equality check predicate on the "mission_id" field. It's identical to MissionIDEQ.
func MissionID(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldMissionID, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.Request {
	return predicate.Request(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.Request {
	return predicate.Request(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.Request {
	return predicate.Request(sql.FieldContainsFold(FieldReason, v))
}

// RequesterEQ applies the EQ predicate on the "requester" field.
func RequesterEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldRequester, v))
}

// RequesterNEQ applies the NEQ predicate on the "requester" field.
func RequesterNEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldRequester, v))
}

// RequesterIn applies the In predicate on the "requester" field.
func RequesterIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldRequester, vs...))
}

// RequesterNotIn applies the NotIn predicate on the "requester" field.
func RequesterNotIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldRequester, vs...))
}

// RequesterGT applies the GT predicate on the "requester" field.
func RequesterGT(v string) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldRequester, v))
}

// RequesterGTE applies the GTE predicate on the "requester" field.
func RequesterGTE(v string) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldRequester, v))
}

// RequesterLT applies the LT predicate on the "requester" field.
func RequesterLT(v string) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldRequester, v))
}

// RequesterLTE applies the LTE predicate on the "requester" field.
func RequesterLTE(v string) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldRequester, v))
}

// RequesterContains applies the Contains predicate on the "requester" field.
func RequesterContains(v string) predicate.Request {
	return predicate.Request(sql.FieldContains(FieldRequester, v))
}

// RequesterHasPrefix applies the HasPrefix predicate on the "requester" field.
func RequesterHasPrefix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasPrefix(FieldRequester, v))
}

// RequesterHasSuffix applies the HasSuffix predicate on the "requester" field.
func RequesterHasSuffix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasSuffix(FieldRequester, v))
}

// RequesterEqualFold applies the EqualFold predicate on the "requester" field.
func RequesterEqualFold(v string) predicate.Request {
	return predicate.Request(sql.FieldEqualFold(FieldRequester, v))
}

// RequesterContainsFold applies the ContainsFold predicate on the "requester" field.
func RequesterContainsFold(v string) predicate.Request {
	return predicate.Request(sql.FieldContainsFold(FieldRequester, v))
}

// MissionIDEQ applies the EQ predicate on the "mission_id" field.
func MissionIDEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldMissionID, v))
}

// MissionIDNEQ applies the NEQ predicate on the "mission_id" field.
func MissionIDNEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldMissionID, v))
}

// MissionIDIn applies the In predicate on the "mission_id" field.
func MissionIDIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldMissionID, vs...))
}

// MissionIDNotIn applies the NotIn predicate on the "mission_id" field.
func MissionIDNotIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldMissionID, vs...))
}

// MissionIDGT applies the GT predicate on the "mission_id" field.
func MissionIDGT(v string) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldMissionID, v))
}

// MissionIDGTE applies the GTE predicate on the "mission_id" field.
func MissionIDGTE(v string) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldMissionID, v))
}

// MissionIDLT applies the LT predicate on the "mission_id" field.
func MissionIDLT(v string) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldMissionID, v))
}

// MissionIDLTE applies the LTE predicate on the "mission_id" field.
func MissionIDLTE(v string) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldMissionID, v))
}

// MissionIDContains applies the Contains predicate on the "mission_id" field.
func MissionIDContains(v string) predicate.Request {
	return predicate.Request(sql.FieldContains(FieldMissionID, v))
}

// MissionIDHasPrefix applies the HasPrefix predicate on the "mission_id" field.
func MissionIDHasPrefix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasPrefix(FieldMissionID, v))
}

// MissionIDHasSuffix applies the HasSuffix predicate on the "mission_id" field.
func MissionIDHasSuffix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasSuffix(FieldMissionID, v))
}

// MissionIDEqualFold applies the EqualFold predicate on the "mission_id" field.
func MissionIDEqualFold(v string) predicate.Request {
	return predicate.Request(sql.FieldEqualFold(FieldMissionID, v))
}

// MissionIDContainsFold applies the ContainsFold predicate on the "mission_id" field.
func MissionIDContainsFold(v string) predicate.Request {
	return predicate.Request(sql.FieldContainsFold(FieldMissionID, v))
}

// HasMission applies the HasEdge predicate on the "mission" edge.
func HasMission() predicate.Request {
	return predicate.Request(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MissionTable, MissionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMissionWith applies the HasEdge predicate on the "mission" edge with a given conditions (other predicates).
func HasMissionWith(preds ...predicate.Mission) predicate.Request {
	return predicate.Request(func(s *sql.Selector) {
		step := newMissionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Request) predicate.Request {
	return predicate.Request(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Request) predicate.Request {
	return predicate.Request(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Request) predicate.Request {
	return predicate.Request(sql.NotPredicates(p))
}
